package Visual;

import EstructurasAuxiliares.ListaArticulo;
import EstructurasAuxiliares.ListaString;
import Logico.Articulo;
import Logico.Controladora;
import java.io.Serializable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 * 
 * @author Alessandro
 */

public class BuscarPorAutor extends javax.swing.JDialog implements Serializable{

    /**
     * Creates new form CargarArchivo
     */
    DefaultTableModel tableModel; //Modelo de la tabla
    DefaultComboBoxModel<String> cbxModel; //Modelo del combo box
    ListaArticulo articulos; //Lista de articulos a imprimir dentro de la tabla
    Articulo articuloSelected; //Este es el articulo seleccionado por el usuario para ver sus estadísticas.
    
    public BuscarPorAutor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        tableModel = new DefaultTableModel();
        cbxModel = new DefaultComboBoxModel<>();
        String[] cabeceraTabla = new String[]{"Titulo", "Cant Autores", "cant Palabras Claves"}; //Nombre de las columnas
        tableModel.setColumnIdentifiers(cabeceraTabla);
        table.setModel(tableModel);
        cbxAutores.setModel(cbxModel);
        cargarCbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scrollArticulo = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxAutores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 530, 10));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollArticulo.setViewportView(table);

        jPanel1.add(scrollArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 790, 300));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Buscar Resumen por Palabra Clave");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 710, 68));

        btnEstadisticas.setText("Ver Detalles");
        btnEstadisticas.setEnabled(false);
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 290, 50));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 290, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("(Elige un Autor)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 310, 40));

        cbxAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAutoresActionPerformed(evt);
            }
        });
        jPanel1.add(cbxAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 360, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        Detalles detalles = new Detalles(Principal.getFrames()[0], true, articuloSelected);
        detalles.setVisible(true);
        btnEstadisticas.setEnabled(false);
        articuloSelected = null;
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        articuloSelected = Controladora.getInstance().getHashTable().buscarArticulo(articulos.getArticuloByIndex(table.getSelectedRow()).getTitulo());
        btnEstadisticas.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void cbxAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAutoresActionPerformed
        ListaArticulo artAux = Controladora.getInstance().getHashTable().obtenerArticulos();
        articulos = new ListaArticulo();
        for (Articulo articulo : artAux.getArticulos()) {
            for (String elemento : articulo.getAutores().getElementos()) {
                if (limpiar(elemento).equalsIgnoreCase(limpiar(cbxModel.getSelectedItem().toString()))) {
                    articulos.agregar(articulo);
                }
            }
        }
        cargarTabla();
    }//GEN-LAST:event_cbxAutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CargarArchivo dialog = new CargarArchivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JComboBox<String> cbxAutores;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollArticulo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(){
        
        tableModel.setRowCount(0);
        TableColumnModel columnModel = table.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(250);
        for (Articulo articulo: articulos.getArticulos()) {
            tableModel.addRow(new Object[]{articulo.getTitulo(), articulo.getAutores().getSize(), articulo.getPalabrasClave().getSize()});
        }      
    }

    private void cargarCbx() {
        ListaString listaAutores = new ListaString();
        ListaArticulo listaArticulos = Controladora.getInstance().getHashTable().obtenerArticulos();
        if (listaArticulos.getArticulos()[0] != null) {
            for (Articulo articulo: listaArticulos.getArticulos()) {
            for (String elemento : articulo.getAutores().getElementos()) {
                if (!contiene(elemento, listaAutores.getElementos())) {
                    listaAutores.agregar(elemento);
                    cbxModel.addElement(elemento);
                    }
                }
            }
        }
    }

    private boolean contiene(String elemento, String[] elementos) {
        
        for (String autor : elementos) {
            if (autor == null) {
                return false;
            }
            if (limpiar(autor).equalsIgnoreCase(limpiar(elemento))) {
                return true;
            }
        } 
        return false;
    }
    
    private String limpiar(String elemento) {
        
        String texto = elemento.replaceAll(" ", "");
        return texto;
    }
}
