package Visual;

import Logico.Articulo;
import Logico.Controladora;
import java.io.Serializable;
import javax.swing.JLabel;

/**
* 
* @author Alessandro
*/

public class Estadisticas extends javax.swing.JDialog implements Serializable{
    
    /**
     * Creates new form CargarArchivo
     */
    
    Articulo articulo;
    public Estadisticas(java.awt.Frame parent, boolean modal, Articulo articuloSelected) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        articulo = articuloSelected;
        previsualizar(articulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollArticulo = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(scrollArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 740, 290));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Estadisticas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollArticulo;
    // End of variables declaration//GEN-END:variables

    private void previsualizar(Articulo articulo) {
        //Agrega las estadísticas del articulo al scroll. Esto permite ver todo el contenido.
        scrollArticulo.getViewport().add(new JLabel(Controladora.getInstance().previsualizarEstadisticas(articulo)));
    }
}
