package Visual;

import Logico.Articulo;
import Logico.Controladora;
import java.awt.event.WindowAdapter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * 
 * @author Alessandro
 */

public class Principal extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form Principal
     */
    private static final long serialVersionUID = 1L;
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAnalizarResumen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarArticulo = new javax.swing.JButton();
        AgregarResumen = new javax.swing.JButton();
        btnBuscarPorPalabraClave = new javax.swing.JButton();
        btnBuscarPorAutor = new javax.swing.JButton();
        btnSalirGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 590));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" Diego Ramos");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 140, 40));

        btnAnalizarResumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnalizarResumen.setText("Analizar Resumen");
        btnAnalizarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarResumenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalizarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 220, 110));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 530, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 40)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistema de Articulos Cientificos");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 28, 980, 70));

        btnBuscarArticulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarArticulo.setText("Buscar Articulo");
        btnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 220, 110));

        AgregarResumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AgregarResumen.setText("Agregar un resumen/articulo");
        AgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarResumenActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, 110));

        btnBuscarPorPalabraClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorPalabraClave.setText("Buscar por palabras Clave");
        btnBuscarPorPalabraClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorPalabraClaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPorPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 220, 110));

        btnBuscarPorAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorAutor.setText("Buscar por Autor");
        btnBuscarPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPorAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 220, 110));

        btnSalirGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalirGuardar.setText("Guardar y Salir");
        btnSalirGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 220, 110));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Menu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 120, 68));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" Alessandro Flammia");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarResumenActionPerformed
        AnalizarResumen analizarResumen = new AnalizarResumen(this, true);
        analizarResumen.setVisible(true);
    }//GEN-LAST:event_btnAnalizarResumenActionPerformed

    private void btnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del articulo", "Buscar Articulo", JOptionPane.OK_OPTION);
        Articulo articulo = null;
        if (nombre != null) {
            articulo = Controladora.getInstance().getHashTable().buscarArticulo(nombre);
        }
        if (articulo != null && !nombre.equalsIgnoreCase("")) {
            Detalles detalles = new Detalles(this, true, articulo);
            //JOptionPane.showMessageDialog(null, Controladora.getInstance().previsualizar(articulo));
            detalles.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo encontrar el Articulo");
        }
    }//GEN-LAST:event_btnBuscarArticuloActionPerformed

    private void AgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarResumenActionPerformed
        CargarArchivo cargarArchivo = new CargarArchivo(this, true);
        cargarArchivo.setVisible(true);
    }//GEN-LAST:event_AgregarResumenActionPerformed

    private void btnBuscarPorPalabraClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorPalabraClaveActionPerformed
        BuscarPorPalabraClave bpc = new BuscarPorPalabraClave(this, true);
        bpc.setVisible(true);
    }//GEN-LAST:event_btnBuscarPorPalabraClaveActionPerformed

    private void btnBuscarPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorAutorActionPerformed
        BuscarPorAutor bpa = new BuscarPorAutor(this, true);
        bpa.setVisible(true);
    }//GEN-LAST:event_btnBuscarPorAutorActionPerformed

    private void btnSalirGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirGuardarActionPerformed
        //Se guardan los datos del sistema en el fichero
        FileOutputStream controladoraArchivo;
        ObjectOutputStream controladoraWrite;
        
        try {
            controladoraArchivo = new FileOutputStream("src/Archivo/datos.dat");
            controladoraWrite = new ObjectOutputStream(controladoraArchivo);
            controladoraWrite.writeObject(Controladora.getInstance());
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        dispose();
    }//GEN-LAST:event_btnSalirGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //Esto carga los datos al sistema cuándo es inciado, si se inicia pro primera vez pues se crea el fichero.
            public void run() {
                FileInputStream controladora;
                FileOutputStream controladora2;
                ObjectInputStream controladoraRead;
                ObjectOutputStream controladoraWrite;

                try {
                    controladora = new FileInputStream ("src/Archivo/datos.dat");
                    controladoraRead = new ObjectInputStream(controladora);
                    Controladora temp = (Controladora)controladoraRead.readObject();
                    Controladora.setControladora(temp);
                    if (Controladora.getInstance().getHashTable().obtenerArticulos().getArticulos()[0] == null) {
                        for (int i = 0; i < 4; i++) {
                            Controladora.getInstance().agregarArticulo(Controladora.getInstance().cargarArchivoResumen("src/ArchivosPrecargados/arch"+(i+1)));
                        }
                    }
                    controladora.close();
                    controladoraRead.close();
                } catch (FileNotFoundException e) {
                        try {
                            controladora2 = new  FileOutputStream("src/Archivo/datos.dat");
                            controladoraWrite = new ObjectOutputStream(controladora2);
                            controladoraWrite.writeObject(Controladora.getInstance());
                            controladora2.close();
                            controladoraWrite.close();
                            for (int i = 0; i < 4; i++) {
                                Controladora.getInstance().agregarArticulo(Controladora.getInstance().cargarArchivoResumen("src/ArchivosPrecargados/arch"+(i+1)));
                            }
                        } catch (FileNotFoundException e1) {
                        } catch (IOException e1) {
                        }
                } catch (IOException e) {
                    
                } catch (ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarResumen;
    private javax.swing.JButton btnAnalizarResumen;
    private javax.swing.JButton btnBuscarArticulo;
    private javax.swing.JButton btnBuscarPorAutor;
    private javax.swing.JButton btnBuscarPorPalabraClave;
    private javax.swing.JButton btnSalirGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

     public void cerrar(){
        Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"Si cierras la aplicación por esta vía los datos no se guardaran, presiona el botón --Guardar y Salir--  ¿Desear salir de igual modo?","Mensaje de Confirmacion" ,
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
        System.exit(0);
        }else{
        }
     }
}
